// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bqpZZfpcLu6VBHua3i26jxZX_lZrD38',
    appId: '1:763029684660:web:9665e0c330798c577ef2e1',
    messagingSenderId: '763029684660',
    projectId: 'spotless-11e3c',
    authDomain: 'spotless-11e3c.firebaseapp.com',
    storageBucket: 'spotless-11e3c.appspot.com',
    measurementId: 'G-FS89HCPKWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD0j2CNRUu2DFTaTuHs3alT-Xki187Oh8',
    appId: '1:763029684660:android:61b4de453e3e50177ef2e1',
    messagingSenderId: '763029684660',
    projectId: 'spotless-11e3c',
    storageBucket: 'spotless-11e3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqrDJnDYnUJz168KYY1Pfp4gVcfKEF9jo',
    appId: '1:763029684660:ios:4750c1df81b90e837ef2e1',
    messagingSenderId: '763029684660',
    projectId: 'spotless-11e3c',
    storageBucket: 'spotless-11e3c.appspot.com',
    iosBundleId: 'com.example.spotlessStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqrDJnDYnUJz168KYY1Pfp4gVcfKEF9jo',
    appId: '1:763029684660:ios:4750c1df81b90e837ef2e1',
    messagingSenderId: '763029684660',
    projectId: 'spotless-11e3c',
    storageBucket: 'spotless-11e3c.appspot.com',
    iosBundleId: 'com.example.spotlessStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_bqpZZfpcLu6VBHua3i26jxZX_lZrD38',
    appId: '1:763029684660:web:11c1b7857cd262e57ef2e1',
    messagingSenderId: '763029684660',
    projectId: 'spotless-11e3c',
    authDomain: 'spotless-11e3c.firebaseapp.com',
    storageBucket: 'spotless-11e3c.appspot.com',
    measurementId: 'G-QDMTBE93X6',
  );
}
